# Generated by Django 5.2.6 on 2026-09-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "region",
                    models.CharField(
                        db_index=True, default="unassigned", max_length=32
                    ),
                ),
                ("last_reported_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "connectivity_status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(null=True)),
                ("error_count", models.PositiveIntegerField(null=True)),
                ("firmware_version", models.CharField(max_length=32, null=True)),
                (
                    "hygiene_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("score_components", models.JSONField(null=True)),
                ("is_poor", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hygiene_score__gte", 0), ("hygiene_score__lte", 100)
                        ),
                        name="stations_score_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reported_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "connectivity_status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=8,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField()),
                ("error_count", models.PositiveIntegerField()),
                ("firmware_version", models.CharField(max_length=32)),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "health_reports",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station", "reported_at"),
                        name="uniq_station_reported_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("connectivity_status__in", ["online", "offline"])
                        ),
                        name="reports_status_valid",
                    ),
                ],
            },
        ),
    ]
